language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - jruby-1.6
  - jruby-1.7

env:
  - ACTIVESUPPORT_VERSION=3.0
  - ACTIVESUPPORT_VERSION=3.1
  - ACTIVESUPPORT_VERSION=3.2

matrix:
  include:
    - rvm: 1.8.7
      env: ACTIVESUPPORT_VERSION=2.3

install:
  - "bundle update"

script: "bundle exec rake ci:spec"
